services: 
  jupyter:
    image: jupyter/pyspark-notebook
    ports:
      - 8888:8888
      - 4040:4040
    user: root
    environment:
      - NB_USER=lab_user
      - CHOWN_HOME=yes
    working_dir: /home/lab_user
    command: ["start-notebook.sh"]
    restart: always
    volumes:
      - .././notebook_data:/home/lab_user/notebook_data

volumes:
  notebook_data:
    external: true